version: 0.2

env:
   variables:
      AWS_REGION: 'us-west-1'
      REACT_APP_USERS_SERVICE_URL: 'http://localhost:5001'

phases:
   install:
      runtime-versions:
         docker: 18
   pre_build:
      commands:
         - echo logging in to ecr...
         - $(aws ecr get-login --no-include-email --region us-east-2)
   build:
      commands:
         - echo building images...
         - >
            docker build \
              -f services/users/Dockerfile.prod \
              -t 510152631726.dkr.ecr.us-east-2.amazonaws.com/test-driven-users:prod \
              ./services/users
         - >
            docker build \
              -f services/client/Dockerfile.prod \
              -t 510152631726.dkr.ecr.us-east-2.amazonaws.com/test-driven-client:prod \
              --build-arg NODE_ENV=production \
              --build-arg REACT_APP_USERS_SERVICE_URL=$REACT_APP_USERS_SERVICE_URL \
              ./services/client
   post_build:
      commands:
         - docker push 510152631726.dkr.ecr.us-east-2.amazonaws.com/test-driven-users:prod
         - docker push 510152631726.dkr.ecr.us-east-2.amazonaws.com/test-driven-client:prod
